apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"generation":1,"labels":{"app":"todo-app"},"name":"todo-dep","namespace":"dowk-22-todo","resourceVersion":"4188","uid":"3d0f298a-229d-4d00-b0f8-f9d17eb1e940"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"todo-app"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"linkerd.io/inject":"enabled"},"labels":{"app":"todo-app"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"client-config"}}],"image":"jeknom/dowk-22-todo-client:1.9","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/","port":3000,"scheme":"HTTP"},"initialDelaySeconds":120,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"client","readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/ready","port":3000,"scheme":"HTTP"},"initialDelaySeconds":60,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{"cpu":"100m","memory":"128Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"},{"envFrom":[{"configMapRef":{"name":"server-config"}},{"secretRef":{"name":"todo-secret"}}],"image":"jeknom/dowk-22-todo-server:2.0","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/ready","port":8081,"scheme":"HTTP"},"initialDelaySeconds":120,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"name":"server","readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/ready","port":8081,"scheme":"HTTP"},"initialDelaySeconds":60,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{"cpu":"100m","memory":"128Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"message":"ReplicaSet \"todo-dep-5d58d96c65\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
    generation: 2
    labels:
      app: todo-app
    name: todo-dep
    namespace: dowk-22-todo
    resourceVersion: "4322"
    uid: 3d0f298a-229d-4d00-b0f8-f9d17eb1e940
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: todo-app
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          linkerd.io/inject: enabled
        labels:
          app: todo-app
      spec:
        containers:
        - envFrom:
          - configMapRef:
              name: client-config
          image: jeknom/dowk-22-todo-client:1.9
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: client
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - envFrom:
          - configMapRef:
              name: server-config
          - secretRef:
              name: todo-secret
          image: jeknom/dowk-22-todo-server:2.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: server
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - message: ReplicaSet "todo-dep-5bd5b9ff4" is progressing.
      reason: ReplicaSetUpdated
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 2
    unavailableReplicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "3"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"generation":2,"labels":{"app":"broadcaster-dep"},"name":"broadcaster-dep","namespace":"dowk-22-todo","resourceVersion":"4058","uid":"388d33e9-1615-4c74-bdf6-5627d17b55c2"},"spec":{"progressDeadlineSeconds":600,"replicas":6,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"broadcaster-dep"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"linkerd.io/inject":"enabled"},"labels":{"app":"broadcaster-dep"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"broadcaster-config"}},{"secretRef":{"name":"todo-broadcaster-secret"}}],"image":"jeknom/dowk-22-todo-broadcaster:2.0","imagePullPolicy":"Always","name":"broadcaster","resources":{"limits":{"cpu":"100m","memory":"128Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":6,"conditions":[{"message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"message":"ReplicaSet \"broadcaster-dep-6b44bb75bc\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":2,"readyReplicas":6,"replicas":6,"updatedReplicas":6}}
    generation: 3
    labels:
      app: broadcaster-dep
    name: broadcaster-dep
    namespace: dowk-22-todo
    resourceVersion: "4563"
    uid: 388d33e9-1615-4c74-bdf6-5627d17b55c2
  spec:
    progressDeadlineSeconds: 600
    replicas: 6
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: broadcaster-dep
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          linkerd.io/inject: enabled
        labels:
          app: broadcaster-dep
      spec:
        containers:
        - envFrom:
          - configMapRef:
              name: broadcaster-config
          - secretRef:
              name: todo-broadcaster-secret
          image: jeknom/dowk-22-todo-broadcaster:2.0
          imagePullPolicy: Always
          name: broadcaster
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 6
    conditions:
    - message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - message: ReplicaSet "broadcaster-dep-5bf89d4468" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 3
    readyReplicas: 6
    replicas: 6
    updatedReplicas: 6
kind: List
metadata: {}
---