# CONFIG
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: dowk-22
data:
  PGDATA: /var/lib/postgresql/data
---
# VOLUME CLAIM
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: dowk-22
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: database-svc
  namespace: dowk-22
spec:
  clusterIP: None
  selector:
    app: postgresapp
  ports:
    - port: 5432
      name: web
---
# STATEFUL SET
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-ss
  namespace: dowk-22
spec:
  serviceName: postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgresapp
  template:
    metadata:
      labels:
        app: postgresapp
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: database-pvc
      containers:
        - name: postgres
          image: postgres
          envFrom:
            - configMapRef:
                name: database-config
            - secretRef:
                name: database-secret
          ports:
            - name: web
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres