apiVersion: v1
kind: Secret
metadata:
    name: todo-secret
    namespace: dowk-22-todo
data:
    DATABASE_URL: ENC[AES256_GCM,data:iZnzSnvAjzyoGEmsptza2Z10k8FZMwji5KET/kEYD9IyUmz/6z5rd6hDlhbkzpcr6deIFxCuTADk5SXrcA2p9w==,iv:a3AQ5ie+KO3SohHuef8YMxC/qOE2zlr7JeXCfvzwAps=,tag:flWuowwbAmH4qfg+/h3Gww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vkf77wk457myzfty0e3pzwswl90kywjtsy6d6f6mcuh6egzdg9ts5dl4ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZW9Ec1o0SkN6NmtSZjJT
            b3RqTTkyR2dqa1NpdG9NUlJaOHVUZ3R5RUNJCmRyVElLdmxaR0c0QjhBcEJYc0o0
            TEl6Z2lqQmNxdGtjbDFWK2hYZ1k4VW8KLS0tIDdxb1piRVZVQnRrNkZiVDJ5Q095
            YkdvaFBEeW9Rc0sxejhRY2RGekFzbUUKAAZil9154yT3CB+sxlkeSlA/0eBLy6Hz
            TqFnroH0Z8b7ZUWgedTw6oi0e00DRL1clxiD6JQ4dCOgH9lXSZ3ylQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-07T18:07:33Z"
    mac: ENC[AES256_GCM,data:/s22AB9lSHriKawwzGbx7aWKNRQhgyv5lI8qnMWr3W4OTCCa2xtwC5wwbvIAqXOYFu1TyQpWPACBQ7qPQjne/4Rg4j/0jTifWY5WVpvWpC8vnafhA3VyGsaTxj/QAwO7BFGjmKi012TbR27N35Er5LzpHx83qOdlvEYaVAK8WHA=,iv:fOxqfkRckcX8NaFABIynN0Am4Ec/LyxPm7I9Fca1DcU=,tag:y11LOOb3GaER9rl34MZkKA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
