apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ping-pong
spec:
  template:
    metadata:
      name: ping-pong-v7
    spec:
      containers:
        - image: jeknom/dowk-22-ping-pong-app:0.6
          envFrom:
            - secretRef:
                name: ping-pong-secret
          ports:
            - containerPort: 8080