apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: CLIENT_IMAGE
    newName: jeknom/dowk-22-todo-client:1.9
  - name: SERVER_IMAGE
    newName: jeknom/dowk-22-todo-server:2.0
  - name: BROADCASTER_IMAGE
    newName: jeknom/dowk-22-todo-broadcaster:2.0
resources:
  - manifests/database.yaml
  - manifests/database-secret.yaml
  - manifests/todo-app.yaml
  - manifests/todo-secret.yaml
  - manifests/todo-broadcaster-secret.yaml