apiVersion: v1
kind: Service
metadata:
  name: todo-server-svc
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - name: client
      port: 2600
      protocol: TCP
      targetPort: 8080